CREATE TABLE shop (
  shop_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  address varchar (50) NULL,
  street varchar (50) NULL,
  city varchar (30) NOT NULL,
  state varchar (30) NOT NULL,
  country varchar(8) NOT NULL,
  menu_id INT NOT NULL,
  queue_num INT NOT NULL,
  max_queue_size INT NOT NULL,
  opening_time varchar (10) NOT NULL,
  closing_time varchar(10) NOT NULL,
  created_by INT NOT NULL,
  create_date DATE NOT NULL,
  modified_date DATE NOT NULL,
  CONSTRAINT shop_pkey PRIMARY KEY (shop_id)
);

CREATE TABLE menu (
  menu_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  items TEXT NOT NULL,
  create_date DATE NOT NULL,
  modified_date DATE NOT NULL,
  CONSTRAINT menu_pkey PRIMARY KEY (menu_id)
);

ALTER TABLE shop ADD CONSTRAINT shop_fkey FOREIGN KEY (menu_id) REFERENCES menu (menu_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE TABLE shop_user (
  user_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_name varchar (50) NOT NULL,
  contact_num varchar (20) NOT NULL,
  contact_email varchar (100) NOT NULL,
  credentials varchar (30) NOT NULL,
  role varchar (10) NOT NULL,
  shop_id INT NOT NULL,
  create_date DATE NOT NULL,
  modified_date DATE NOT NULL,
  CONSTRAINT shop_user_pkey PRIMARY KEY (user_id)
);

ALTER TABLE shop_user ADD CONSTRAINT shop_user_fkey FOREIGN KEY (shop_id) REFERENCES shop (shop_id) ON UPDATE NO ACTION ON DELETE NO ACTION;