CREATE TABLE orders (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  customer_id INT NOT NULL,
  item varchar (50) NOT NULL,
  price INT NOT NULL,
  time_to_prep INT NOT NULL,
  status varchar (20) NOT NULL,
  shop_id INT NOT NULL,
  create_date DATE NOT NULL,
  modified_date DATE NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (id)
);

ALTER TABLE orders ADD CONSTRAINT order_fkey FOREIGN KEY (shop_id) REFERENCES shop (shop_id) ON UPDATE NO ACTION ON DELETE NO ACTION;