CREATE TABLE customer (
  customer_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  customer_name varchar (50) NOT NULL,
  contact_num varchar (20) NOT NULL,
  contact_email varchar (100) NOT NULL,
  credentials varchar (30) NOT NULL,
  address varchar (50) NULL,
  street varchar (50) NULL,
  city varchar (30) NOT NULL,
  state varchar (30) NOT NULL,
  country varchar(8) NOT NULL,
  create_date DATE NOT NULL,
  modified_date DATE NOT NULL,
  CONSTRAINT cust_pkey PRIMARY KEY (customer_id)
);
